using Telerik.DataSource;
using IdentityServer.Abstraction.DTO.ApiResources;
using IdentityServer.Abstraction.DTO.Clients;
using IdentityServer.Abstraction.DTO.History;
using IdentityServer.Abstraction.DTO.Import;
using IdentityServer.Abstraction.DTO.SystemPermissions;
using IdentityServer.Abstraction.Entities;
using IdentityServer.Abstraction.Entities.EntraEntities;
using IdentityServer.Abstraction.Entities.IdentityServerConfig.SystemPermissions;
using IdentityServer.AdminPortal.Web.Models;

namespace IdentityServer.AdminPortal.Web.Services;

public interface IAdminApiService
{
    Task<ApiCallResult<SystemPermissionDtoRead>> GetSystemPermission(int id);
    Task<ApiCallResult<SystemPermissionDtoRead>> CreateSystemPermission(SystemPermissionDtoCreate systemPermission);
    Task<ApiCallResult<SystemPermissionDtoRead>> UpdateSystemPermission(SystemPermissionDtoUpdate systemPermission);
    Task<ApiCallResult<int>> DeleteSystemPermission(SystemPermissionDtoRead systemPermission);
    Task<ApiCallResult<SystemPermissionEnvironmentDtoRead>> GetSystemPermissionEnvironment(int id);
    Task<ApiCallResult<string[]>> GetSystemPermissionEnvironmentContacts(int id);
    Task<ApiCallResult<DataEnvelope<SystemPermissionEnvironmentDtoRead>>> GetSystemPermissionEnvironmentsPaged(DataSourceRequest request);
    Task<ApiCallResult<SystemPermissionDtoRead>> CreateSystemPermissionEnvironment(SystemPermissionEnvironmentDtoCreate env);
    Task<ApiCallResult<int>> DeleteSystemPermissionEnvironment(SystemPermissionEnvironmentDtoRead env);
    Task<ApiCallResult<SystemPermissionRoleDtoRead>> CreateSystemPermissionRole(SystemPermissionRoleDtoCreate role);
    Task<ApiCallResult<SystemPermissionRoleDtoRead>> UpdateSystemPermissionRole(SystemPermissionRoleDtoUpdate role);
    Task<ApiCallResult<int>> DeleteSystemPermissionRole(SystemPermissionRoleDtoRead role);
    Task<ApiCallResult<ClientDtoRead>> GetClient(int id);
    Task<ApiCallResult<ClientDtoRead>> CreateClient(ClientDtoCreate app);
    Task<ApiCallResult<ClientDtoRead>> CloneClient(ClientDtoClone app);
    Task<ApiCallResult<ClientDtoRead>> UpdateClient(ClientDtoUpdate app);
    Task<ApiCallResult<int>> DeleteClient(ClientDtoRead app);
    Task<ApiCallResult<ClientPropertySecretValueDtoRead>> AddClientSecret(ClientPropertySecretDtoCreate secret);
    Task<ApiCallResult<int>> DeleteClientSecret(ClientPropertySecretDtoRead secret);
    Task<ApiCallResult<ClientPropertyGrantDtoRead>> AddClientGrant(ClientPropertyGrantDtoCreate grant);
    Task<ApiCallResult<int>> DeleteClientGrant(ClientPropertyGrantDtoRead grant);
    Task<ApiCallResult<ClientPropertyEntraAppDtoRead>> AddClientEntraApp(ClientPropertyEntraAppDtoCreate entraApp);
    Task<ApiCallResult<int>> DeleteClientEntraApp(ClientPropertyEntraAppDtoRead entraApp);
    Task<ApiCallResult<ClientPropertyScopeDtoRead>> AddClientScope(ClientPropertyScopeDtoCreate scope);
    Task<ApiCallResult<int>> DeleteClientScope(ClientPropertyScopeDtoRead scope);
    Task<ApiCallResult<ClientPropertyRedirectUriDtoRead>> AddClientRedirectUri(ClientPropertyRedirectUriDtoCreate redirect);
    Task<ApiCallResult<int>> DeleteClientRedirectUri(ClientPropertyRedirectUriDtoRead redirect);
    Task<ApiCallResult<ClientPropertyPostLogoutRedirectUriDtoRead>> AddClientPostLogoutRedirectUri(ClientPropertyPostLogoutRedirectUriDtoCreate postLogoutRedirect);
    Task<ApiCallResult<int>> DeleteClientPostLogoutRedirectUri(ClientPropertyPostLogoutRedirectUriDtoRead postLogoutRedirect);
    Task<ApiCallResult<ClientPropertyCorsOriginDtoRead>> AddClientCorsUri(ClientPropertyCorsOriginDtoCreate cors);
    Task<ApiCallResult<int>> DeleteClientCorsUri(ClientPropertyCorsOriginDtoRead cors);
    Task<ApiCallResult<ClientPropertyRoleDtoRead>> AddClientRole(ClientPropertyRoleDtoCreate role);
    Task<ApiCallResult<int>> DeleteClientRole(ClientPropertyRoleDtoRead role);
    Task<ApiCallResult<ClientPropertyRoleMappingDtoRead>> AddClientRoleMapping(ClientPropertyRoleMappingDtoCreate roleMapping);
    Task<ApiCallResult<int>> DeleteClientRoleMapping(ClientPropertyRoleMappingDtoRead roleMapping);
    Task<ApiCallResult<OperationStatus>> ImportClientRoles(ClientDtoRead client, ClientRoleImportDto roles);
    Task<ApiCallResult<OperationStatus>> ValidateImportClientRoles(ClientDtoRead client, ClientRoleImportDto roles);
    Task<ApiCallResult<ApiResourceDtoRead>> GetApiResource(int id);
    Task<ApiCallResult<ApiResourceDtoRead>> CreateApiResource(ApiResourceDtoCreate app);
    Task<ApiCallResult<ApiResourceDtoRead>> CloneApiResource(ApiResourceDtoClone app);
    Task<ApiCallResult<ApiResourceDtoRead>> UpdateApiResource(ApiResourceDtoUpdate app);
    Task<ApiCallResult<int>> DeleteApiResource(ApiResourceDtoRead api);
    Task<ApiCallResult<ApiResourcePropertySecretValueDtoRead>> AddApiResourceSecret(ApiResourcePropertySecretDtoCreate secret);
    Task<ApiCallResult<int>> DeleteApiResourceSecret(ApiResourcePropertySecretDtoRead secret);
    Task<ApiCallResult<ApiResourcePropertyScopeDtoRead>> AddApiResourceScope(ApiResourcePropertyScopeDtoCreate scope);
    Task<ApiCallResult<ApiResourcePropertyScopeDtoRead>> UpdateApiResourceScope(ApiResourcePropertyScopeDtoUpdate scope);
    Task<ApiCallResult<int>> DeleteApiResourceScope(ApiResourcePropertyScopeDtoRead scope);
    Task<ApiCallResult<ApiResourcePropertyRoleDtoRead>> AddApiResourceRole(ApiResourcePropertyRoleDtoCreate role);
    Task<ApiCallResult<int>> DeleteApiResourceRole(ApiResourcePropertyRoleDtoRead role);
    Task<ApiCallResult<ApiResourcePropertyRoleMappingDtoRead>> AddApiResourceRoleMapping(ApiResourcePropertyRoleMappingDtoCreate roleMapping);
    Task<ApiCallResult<int>> DeleteApiResourceRoleMapping(ApiResourcePropertyRoleMappingDtoRead roleMapping);
    Task<ApiCallResult<OperationStatus>> ImportApiResourceRoles(ApiResourceDtoRead apiResource, ApiResourceRoleImportDto roles);
    Task<ApiCallResult<OperationStatus>> ValidateImportApiResourceRoles(ApiResourceDtoRead apiResource, ApiResourceRoleImportDto roles);
    Task<ApiCallResult<DataEnvelope<User>>> FindEligibleAssignmentsPaged(DataSourceRequest gridRequest, int envId, SystemPermissionRoleType roleType);
    Task<ApiCallResult<GroupResponse>> SearchGroups(string searchValue, string? skipToken);
    Task<ApiCallResult<UserResponse>> SearchUsers(string searchValue);
    Task<ApiCallResult<UserResponse>> GetUserById(string userId);
    Task<ApiCallResult<Diagnostics>> GetDiagnostics();
    Task<ApiCallResult<DataEnvelope<ClientShortDtoRead>>> GetClientsPaged(DataSourceRequest gridRequest);
    Task<ApiCallResult<DataEnvelope<ClientShortDtoRead>>> GetClientsByScopePaged(string scopeName, DataSourceRequest gridRequest);
    Task<ApiCallResult<DataEnvelope<ApiResourceShortDtoRead>>> GetApiResourcesPaged(DataSourceRequest gridRequest);
    Task<ApiCallResult<DataEnvelope<SystemPermissionShortDtoRead>>> GetSystemPermissionsPaged(DataSourceRequest gridRequest);

    Task<ApiCallResult<HistoryResponseDto>> GetClientHistory(int clientId);
    Task<ApiCallResult<HistoryResponseDto>> GetSystemPermissionHistory(int systemPermissionId);
    Task<ApiCallResult<HistoryResponseDto>> GetApiResourceHistory(int apiResourceId);
}
